### ISSUE TITLE
Nova 3 Backwards Compatibility

### ISSUE THREAD

**Issue by karsonenns** [Muetze42/nova-iframe-popup#4]
Great package, any chance of getting Nova 3 / PHP 7.4 support?

**Comment by Muetze42** [comment]
II'll have to see how I install Nova 3.
I think nothing stands in the way of compatibility if the VUE part works.

**Comment by Muetze42** [comment]
I can't install Nova 3.
I've tested it with Laravel 7.24 and PHP 7.4.

> Root composer.json requires laravel/nova, it could not be found in any version, there may be a typo in the package name.

**Comment by lugamb1** [comment]
Any updates on compatibility?

**Comment by Muetze42** [comment]
No. I also don't plan to run the version on an outdated version at the moment.
