### ISSUE TITLE
map-pin heroicon not working?

### ISSUE THREAD

**Issue by HeadStudios** [Muetze42/nova-iframe-popup#6]
Hi,

Your nova extension is amazing - I just thought I'd point out a minor issue I just faced. When using the ->icon() function it works with 'map' but not 'map-icon' - even though this is available on Heroicons - any reason for why this would be?

https://share.zight.com/Jrum8NEJ

Thank you!

**Comment by Muetze42** [comment]
Nova use Heroicons V1:



https://v1.heroicons.com/

Maybe it would be an idea to integrate Heroicons 2 as an alternative.

**Comment by HeadStudios** [comment]
Thank you so much for clarifying! I can confirm I changed icon() argument to 'location-marker' and it works beautifully. Thank you once again! Closing the issue now.

**Comment by Muetze42** [comment]
We'll see. Maybe I will additionally integrate Heroicons 2.
